title: Boda Huo
description: Robot learning, visuo-tactile sensing, whole-body humanoid control
url: "https://bodah-silv.github.io"        # set to https://bodah-silv.github.io after publishing
baseurl: ""    # leave blank for user/organization site
theme: minima
markdown: kramdown
kramdown:
  input: GFM
minima:
  social_links:
    - { platform: github,   user_url: "https://github.com/bodah-silv" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/boda-huo-a795781a1/" }

# _config.yml (or _data/navigation.yml)
nav:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Research
    url: /research/
  - text: Course Projects
    url: /course-projects/
  - text: Resume
    url: /resume/

